defaults:
  - prefix_tb_hypergrid
  - _self_

seed: 0
use_jit: True
use_comet: True
batch_size: 512
eval_frequency: 200

comet:
  api_key: ${oc.env:COMETML_API_KEY}
  project_name: gfn_ot
  workspace: ${oc.env:COMETML_WORKSPACE}
  exp_name: ""